### ISSUE TITLE
volume not persistent

### ISSUE THREAD

**Issue by Castelsarrasin** [aborroy/alfresco-identity-service-to-keycloak#1]
Hi, thank you very much for this share !

I practice a new environnement on ubuntu 22 with alfresco 7.4 with docker.
I added this git and mixed this identity service.
All is up, expect when i configure a kerberos or LDAP  in "User federation" in realm "alfresco" in keycloak and restart the docker, i lost everything.

Is it possible to keep the keycloak configuration after a docker compose down and a docker compose up ?
Actually it isn't.

Is it the 
"       command: "
            start --import-realm --hostname=$HOST_IP --hostname-port=8999 --http-enabled=true --hostname-strict-https=false
"

who import and delete all my configuration ?

Thank you.

**Comment by aborroy** [comment]
https://github.com/aborroy/alfresco-identity-service-to-keycloak/blob/main/alfresco-community-aims/compose.yaml#L135

**Comment by Castelsarrasin** [comment]
When i comment this line, i have no-more alfresco realm.
I have to add it on the create_volume.sh script ?
If yes, could you give me the exemple please ?
i know the user is keycloak and permission to 1000

**Comment by Castelsarrasin** [comment]
My ./start.sh for docker compose who contained "docker-compose up --build --force-recreate".
I do that to be sure nothing would be delete, could you tell me if it's possible to have persistent identity service with docker same if i --build --force-recreate ? But id i docker compose down and up it keeps datas.

**Comment by Castelsarrasin** [comment]
finally it wasn't my volume, but the database who wasn't persistent i had to add keycloak database elements.
Thank you
