### ISSUE TITLE
support for oidc with UI configuration (was: doesn't work in general)

### ISSUE THREAD

**Issue by lonestaritaly** [aborroy/alfresco-identity-service-to-keycloak#3]
Hello,
I don't understand why this doesn't work for me.

I expect that when Alfresco is configured with 

 ```
               -Dauthentication.chain=identity-service1:identity-service
                -Didentity-service.enable-basic-auth=true
                -Didentity-service.auth-server-url=https://my-keycloak.server.it
                -Didentity-service.realm=alfresco
                -Didentity-service.resource=alfresco
```
and I access in the browser to https://my-alfresco.it or https://my-alfresco.it/share I should not see the traditional Alfresco login pages but I should be redirected to my Keycloak realm login page, asked the keycloak credentials, and after that I should be in the Alfresco dashboard with the user that I have authenticated.

Instead, when I open those urls, I am presented the usual Alfresco login pages (for ACS or for Share) where the keycloak credentials do not work, and the ntlm credentials do not work as well because that authentication method is not enabled.

What am I doing wrong?

**Comment by aborroy** [comment]
Let me know if the new sample works for you: https://github.com/aborroy/alfresco-identity-service-to-keycloak/tree/main/alfresco-community-keycloak-ui

**Comment by lonestaritaly** [comment]
Thanks for your additions!

Everything works now except one thing: the redirect_uri that is passed to keycloak when authenticating from https://myalfresco.it/share uses the uses the internal protocol and port, instead of the external one.

`https://mykeycloak.it/realms/alfresco/protocol/openid-connect/auth?response_type=code&client_id=alfresco&scope=openid&state=<bla.bla.bla>&redirect_uri=http://myalfresco.it:82/share/page/&nonce=<bla.bla.bla>`

instead it should be:

`https://mykeycloak.it/realms/alfresco/protocol/openid-connect/auth?response_type=code&client_id=alfresco&scope=openid&state=<bla.bla.bla>&redirect_uri=https://myalfresco.it/share/page/&nonce=<bla.bla.bla>`

I have:`

                -Dshare.context=share
                -Dshare.host=myalfresco.it
                -Dshare.port=443
                -Dshare.protocol=https 
`

in both the alfresco and share service definitions, but it doesn't make a difference.

When I access the ACS url at https://myalfresco.it/ the redirect_uri to keycloak is correct.

**Comment by aborroy** [comment]
You may add `aims.redirectURI` to environment variables in https://github.com/aborroy/alfresco-identity-service-to-keycloak/blob/main/alfresco-community-keycloak-ui/compose.yaml#L65

Something like:

```
-Daims.redirectURI=https://myalfresco.it/share/page/
```

>> I guess that is only available for `master` branch: https://github.com/Alfresco/alfresco-community-share/blob/master/share/src/main/resources/share-config.properties#L15

**Comment by aborroy** [comment]
Yes, it will be only available in the next Share release:
https://github.com/Alfresco/alfresco-community-share/commit/ca11bc1e4e654725995caec041232b43e97e45f5

**Comment by lonestaritaly** [comment]
ok thanks, at least I know it's not something that depends on my configuration.
I will wait next release.

**Comment by lonestaritaly** [comment]
I've found that integrating the config/nginx.conf with:

```
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
```

the current released version of Share generates the correct redirectURI and the SSO login works (without -Daims.redirectURI of course)

**Comment by aborroy** [comment]
Great, thanks for your contribution @lonestaritaly 

I've added those lines in sample configuration provided in this project.

Feel free to close this issue if you think everything is covered.
