### ISSUE TITLE
 Issue with ACA Blank Page and 400 Status Codes in alfresco-community-keycloak-ui

### ISSUE THREAD

**Issue by dnenadd** [aborroy/alfresco-identity-service-to-keycloak#4]
Dear @aborroy,

I am trying to set up the solution from the alfresco-community-keycloak-ui folder and run ACA on http://localhost:8080/content-app. However, after logging in (for both users test and admin), I encounter a nearly blank page. The application logs indicate that the server responded with a 400 status code for all resource requests.

Could you please provide guidance on how to resolve this issue?

Thank you in advance for your assistance.

Best regards,
Nenad Djurkovic

**Comment by aborroy** [comment]
Are you setting your host ip in https://github.com/aborroy/alfresco-identity-service-to-keycloak/blob/main/alfresco-community-keycloak-ui/.env#L15?

**Comment by dnenadd** [comment]
Yes. I set up my local IP adress.

**Comment by dnenadd** [comment]
First of all, I apologize. I didn't remove the volumes after making some changes in Keycloak, so those changes were still present. The example is now working, and ACA is functioning properly. However, I'm still having trouble starting Alfresco Share. When I try to access it via http://localhost:8080/share, it redirects me to http://localhost/share/page

**Comment by aborroy** [comment]
This has been solved in https://github.com/aborroy/alfresco-identity-service-to-keycloak/issues/3
